final Map<String, Map<String, String>> appTranslations = {
  'en': {
    'app_name': 'Nix',
    'welcome': 'Welcome',
    'songs': 'Songs',
    'favorites': 'Favorites',
    'settings': 'Settings',
    'choose_language': 'Choose Language',
    'appearance': 'Appearance',
    'dark_mode': 'Dark Mode',
    'light_mode': 'Light Mode',
    'system_mode': 'System Default',
    'color_scheme': 'Color Scheme',
    'about': 'About',
    'app_info': 'App Info',
    'version': 'Version',
    'developer': 'Developer',
    'license': 'License',
    'open_source': 'Open Source',
    'play': 'Play',
    'pause': 'Pause',
    'next': 'Next',
    'previous': 'Previous',
    'shuffle': 'Shuffle',
    'repeat': 'Repeat',
    'now_playing': 'Now Playing',
    'no_songs': 'No songs found.',
    'search': 'Search Songs',
    'your_name': 'Your Name',
    'enter_name': 'Enter your name',
    'save': 'Save',
    'language': 'Language',
    'contact': 'Contact',

    // General actions
    'clear_data': 'Clear Data',
    'warning': 'Warning!',
    'delete_warning_msg':
        'Are you sure you want to delete all data? This cannot be undone.',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'more': 'More',
    'github': 'GitHub',
    'email': 'Email',

    // Theme
    'theme_settings': 'Theme Settings',
    'theme_mode': 'Theme Mode',
    'light': 'Light',
    'dark': 'Dark',
    'system_default': 'System Default',
    'theme_colors': 'Theme Colors',
    'pick_color': 'Pick Color',
    'default_color_note': 'Default color is Blue, under the Pink color.',
    'choose_color': 'Choose color',
    'select': 'Select',

    // About & Features
    'package': 'Package',
    'description':
        'Nix is an open-source local music player built with Flutter. '
        'It offers a sleek UI, fast performance, and offline playback with features like '
        'favorites, shuffle, repeat, theme customization, and a responsive mini-player. '
        'Fully free, private, and customizable. Available on GitHub and coming soon to Play Store.',

    'features': 'Features:',
    'fea1': ' Local Music Playback - ',
    'featu1': 'Plays audio from your device.',
    'fea2': ' Favorites Management - ',
    'featu2': 'Easily add/remove favorite tracks.',
    'fea3': ' Search & Sort - ',
    'featu3': 'Find songs quickly by name or artist.',
    'fea4': ' Shuffle & Repeat - ',
    'featu4': 'Flexible playback options.',
    'fea5': ' Custom Themes - ',
    'featu5': 'Light/Dark/System + color picker.',
    'fea6': ' Responsive MiniPlayer - ',
    'featu6': 'Expandable with smooth animations.',
    'fea7': ' Open Source - ',
    'featu7': 'Free, no ads, full transparency on GitHub.',
    'fea8': ' Future Releases - ',
    'featu8': 'Coming soon to F-Droid and Google Play.',
    'developer_name': 'BawiCeu',
    'open_source_licenses': 'Open Source Licenses',
    'privacy_policy': 'Privacy Policy',
    'source_code_on_gitHub': 'Source Code on GitHub',

    // Player UI
    'no_favorites_songs_yet': 'No favorites songs yet.',
    'songs_nav': 'Songs',
    'favorites_nav': 'Favorites',
    'playlist_nav': 'Playlist',
    'search_hint': 'Search..',
    'user': 'User',
    'default': 'Default',
    'title_az_sort': 'Title (A-Z)',
    'title_za_sort': 'Title (Z-A)',
    'artist_sort': 'Artist',
    'duration_sort': 'Duration (Shortest First)',
    'album': 'Album: ',
    'duration': 'Duration: ',
    'size': 'Size: ',
    'path': 'Path: ',
    'close': 'Close',
    'unknown_device': 'Unknown device',
    'lyrics': 'Lyrics',
    'upcoming_list': 'UpComing List',
    'song_details': 'Song Details',
    'share': 'Share',
    'favorite': 'Favorite',

    //Miniplayer
    'up_coming': 'UpComing',
  },

  'bur': {
    'app_name': 'နစ်စ်',
    'welcome': 'ကြိုဆိုပါတယ်',
    'songs': 'သီချင်းများ',
    'favorites': 'အနှစ်သက်ဆုံး',
    'settings': 'ဆက်တင်',
    'choose_language': 'ဘာသာစကား ရွေးချယ်ပါ',
    'appearance': 'အသွင်အပြင်',
    'dark_mode': 'အမည်းနက်',
    'light_mode': 'အဖြူအလင်း',
    'system_mode': 'စနစ်အလိုက်',
    'color_scheme': 'အရောင်အမျိုးအစား',
    'about': 'အကြောင်းအရာ',
    'app_info': 'အက်ပ်အကြောင်း',
    'version': 'ဗားရှင်း',
    'developer': 'ဖန်တီးသူ',
    'license': 'လိုင်စင်',
    'open_source': 'အခမဲ့ အရင်းအမြစ်',
    'play': 'ဖွင့်မယ်',
    'pause': 'ရပ်မယ်',
    'next': 'နောက်တစ်ပုဒ်',
    'previous': 'နောက်ဆုံးတစ်ပုဒ်',
    'shuffle': 'အလျားလိုက်ဖွင့်',
    'repeat': 'ထပ်ဖွင့်',
    'now_playing': 'ယခုဖွင့်နေသည်',
    'no_songs': 'သီချင်းမရှိပါ',
    'search': 'သီချင်းရှာရန်',
    'your_name': 'သင်၏နာမည်',
    'enter_name': 'နာမည်ထည့်ပါ',
    'save': 'သိမ်းမယ်',
    'language': 'ဘာသာစကား',
    'privacy_policy': 'ကိုယ်ရေးအချက်အလက် မူဝါဒ',
    'contact': 'ဆက်သွယ်ရန်',

    // General actions
    'clear_data': 'ဒေတာများ ဖျက်ရန်',
    'warning': 'သတိပေးချက်!',
    'delete_warning_msg':
        'ဒေတာအားလုံးကို ဖျက်ချင်ပါသလား? ဤလုပ်ဆောင်မှုကို ပြန်လည်မရနိုင်ပါ။',
    'cancel': 'မလုပ်တော့',
    'delete': 'ဖျက်မယ်',
    'more': 'နောက်ထပ်',
    'github': 'ဂစ်ဟပ်',
    'email': 'အီးမေးလ်',

    // Theme
    'theme_settings': 'အရောင်အပြင်အဆင်',
    'theme_mode': 'အရောင် စနစ်',
    'light': 'အလင်း',
    'dark': 'အမှောင်',
    'system_default': 'စနစ်အလိုက်',
    'theme_colors': 'အရောင်များ',
    'pick_color': 'အရောင်ရွေးချယ်ပါ',
    'default_color_note':
        'မူလအရောင်သည် အပြာရောင်ဖြစ်ပြီး ပန်းရောင်အောက်တွင်ရှိသည်။',
    'choose_color': 'အရောင်ရွေးပါ',
    'select': 'ရွေးချယ်',

    // About & Features
    'package': 'ပက်ကေ့ချ်',
    'description':
        'Nix သည် Flutter ဖြင့် ဖန်တီးထားသော open-source သီချင်းပလေယာ ဖြစ်သည်။ '
        'လှပသော UI၊ မြန်ဆန်သော စွမ်းဆောင်ရည်နှင့် အင်တာနက်မလိုအပ်သော ဖွင့်နိုင်ပါတယ်။ '
        'အနှစ်သက်ဆုံး၊ အလျားလိုက်၊ ထပ်ဖွင့်၊ အရောင်စနစ်ပြောင်းလဲနိုင်မှု၊ MiniPlayer တုန့်ပြန်မှုကဲ့သို့ '
        'အင်္ဂါရပ်များကို ထည့်သွင်းထားတယ်။ အခမဲ့၊ လုံခြုံမှုကောင်း၊ ပြင်ဆင်နိုင်ပါတယ်။ GitHub၊ F-Droid တွင် ရရှိနိုင်ပြီး Play Store တွင် မကြာမီ ထုတ်ပြန်ပါမည်။',

    'features': 'အင်္ဂါရပ်များ:',
    'fea1': ' ဖုန်းထဲကများ သီချင်းဖွင့်ခြင်း - ',
    'featu1': 'သင့်ဖုန်းထဲမှ သီချင်းများဖွင့်နိုင်သည်။',
    'fea2': ' အနှစ်သက်ဆုံး စီမံမှု - ',
    'featu2': 'အလွယ်တကူ အနှစ်သက်ဆုံးများ ထည့်/ဖယ် နိုင်သည်။',
    'fea3': ' ရှာဖွေရေး & စီမံခြင်း - ',
    'featu3': 'သီချင်းအမည် သို့မဟုတ် အဆိုတော်အမည်ဖြင့် သီချင်းရှာနိုင်သည်။',
    'fea4': ' အလျားလိုက် & ထပ်ဖွင့် - ',
    'featu4': 'အဆင်ပြေသော ဖွင့်ခြင်းရွေးချယ်စရာများ။',
    'fea5': ' အရောင်စနစ်ထည့်သွင်းနိုင်သည် - ',
    'featu5': 'အလင်း/အမှောင်/စနစ် + အရောင်ရွေးချယ်မှု။',
    'fea6': ' MiniPlayer တုန့်ပြန်မှု - ',
    'featu6': 'ဖုန်းမှန်အပြည့် animation နဲ့ပြသ။',
    'fea7': ' အခမဲ့ အရင်းအမြစ် - ',
    'featu7': 'အခမဲ့၊ ကြော်ငြာမပါ၊ GitHub တွင် ဖွင့်လှစ်ထားသည်။',
    'fea8': ' အနာဂတ်ထုတ်လုပ်မှု - ',
    'featu8': 'F-Droid နှင့် PlayStore တွင် ထုတ်ပြန်မည်။',
    'developer_name': 'BawiCeu',
    'open_source_licenses': 'အခမဲ့ အရင်းအမြစ် လိုင်စင်များ',
    'source_code_on_gitHub': 'GitHub တွင် အရင်းအမြစ်',

    // Player UI
    'no_favorites_songs_yet': 'နှစ်သက်တဲ့ သီချင်းမရှိသေးပါ။',
    'favorite_songs': 'နှစ်သက်တဲ့ သီချင်းများ',
    'songs_nav': 'သီချင်းများ',
    'favorites_nav': 'အနှစ်သက်ဆုံး',
    'playlist_nav': 'သီချင်းစာရင်း',
    'search_hint': 'ရှာရန်..',
    'user': 'အသုံးပြုသူ',
    'default': 'မူလ',
    'title_az_sort': 'သီချင်းအမည် (က-အ)',
    'title_za_sort': 'သီချင်းအမည် (အ-က)',
    'artist_sort': 'အဆိုတော် နာမည်',
    'duration_sort': 'အချိန် (အတိုဆုံး)',
    'album': 'အယ်လ်ဘမ်: ',
    'duration': 'ကြာချိန်: ',
    'size': 'အရွယ်စား: ',
    'file_type': 'ဖိုင်အမျိုးစား: ',
    'path': 'တည်နေရာ: ',
    'close': 'ပိတ်မယ်',
    'favroite_songs': 'နှစ်သက်သော သီချင်းများ',
    'unknown': 'အမည်မသိ',
    'unknown_device': 'အမည်မသိ စက်',
    'lyrics': 'စာသား',
    'upcoming_list': 'လာမည့်စာရင်း',
    'song_details': 'သီချင်း အသေးစိတ်',
    'share': 'မျှဝေ',
    'favorite': 'အနှစ်သက်ဆုံး',

    //Miniplayer
    'up_coming': 'အကြာမီ လာမည်',
  },
  'hakha': {
    'app_name': 'Nix',
    'welcome': 'Welcome',
    'songs': 'Hla',
    'favorites': 'Na duhbik',
    'settings': 'Remh nak',
    'choose_language': 'Hawlh thim',
    'appearance': 'Muisam',
    'dark_mode': 'A mui',
    'light_mode': 'A ceu',
    'system_mode': 'System in',
    'color_scheme': 'Color',
    'about': 'Thu',
    'app_info': 'App kawng',
    'version': 'Version',
    'developer': 'Sertu',
    'license': 'License',
    'open_source': 'Open Source',
    'play': 'Phawnh',
    'pause': 'Din',
    'next': 'Hla hmai',
    'previous': 'Hla hnu',
    'shuffle': 'Amah tein',
    'repeat': 'Phawnh than',
    'now_playing': 'Phawnh Liau',
    'no_songs': 'Hla an um lo',
    'search': 'Hla hawl',
    'your_name': 'Na min',
    'enter_name': 'Na min hawng tial',
    'save': 'Thak',
    'language': 'Hawlh',
    'privacy_policy': 'Dann leh Pumpak',
    'contact': 'Chawnnak ding',
    ///////////
    'clear_data': 'Data Hlawnh',
    'warning': 'Thei herih nak!',
    'delete_warning_msg':
        'Data adih lak in hlawnh dingin nafiang maw? Lak than ngah loh',
    'cancel': 'Tuahthan loh',
    'delete': 'Hlawnh',
    'more': 'Adang',
    'github': 'GitHub',
    'email': 'Email',
    'theme_settings': 'Theme Remhnak',
    'theme_mode': 'Theme Mode',
    'light': 'A ceu',
    'dark': 'A mui',
    'system_default': 'System i um ciami',
    'theme_colors': 'Theme Colors',
    'pick_color': 'Color thimh nak',
    'default_color_note': 'Default a ummi cu Blue a si, Pink a Tangah ah um.',
    'choose_color': 'Color hawng thim',
    'select': 'Ka thim',
    /////////////////////////////////////////////
    'features': 'HmanThatNak :',
    'fea1': ' Local Music Playback - ',
    'featu1': 'Device chungi um mi hla pawl phawnh khawh a si.',
    'fea2': ' Duhbik Hla - ',
    'featu2': 'Awl tein Duh mi pawl remh khawh a si',
    'fea3': ' Kawl & Remh ngah - ',
    'featu3': 'Hla leh a saktu min in kawl khawh a si.',
    'fea4': ' Amahtein & Phawnh_than - ',
    'featu4': 'Amahten athim , Phawnh than Khawh si.',
    'fea5': ' Duahdanin Theme remh khawh - ',
    'featu5': 'Aceu/Amui/System_in + duhmi color thimkhawh si.',
    'fea6': ' Responsive MiniPlayer - ',
    'featu6': 'Expandable with smooth animations.',
    'fea7': ' Source Code hi aman um lo - ',
    'featu7': 'A free i,ads a um loh , duh cun GitHub ah lak khawh a si.',
    'fea8': ' Hmailei chuak nak - ',
    'featu8': 'F-Droid leh Google Play ah offical in a vun chuak te la.',
    'contributors': 'Thawh tu le hna',
    'developer_name': 'BawiCeu',
    'open_source_comu': 'Kan Open Source Community',
    'check_for_updates': 'AThar chuak nak check',
    'open_source_licenses': 'Open Source licenses',
    'source_code_on_gitHub': 'GitHub i Source Code',
    //////
    'no_favorites_songs_yet': 'Duhbik mi hla um hrih a loh.',
    'favorite_songs': 'Duhcem mi hla',
    'songs_nav': 'Hla',
    'favorites_nav': 'Duhbik',
    'playlist_nav': 'Play List',
    'search_hint': 'Kawl nak..',
    'user': 'Hman tu',
    'default': 'Uncia mi',
    'title_az_sort': 'Hlamin (A-Z)',
    'title_za_sort': 'Hlamin (Z-A)',
    'artist_sort': 'Saktumin (A-Z)',
    'duration_sort': 'Hla caan (Atawi cem mi hmasa)',
    'album': 'Album: ',
    'duration': 'Hla caan: ',
    'size': 'Size: ',
    'path': 'Umnak: ',
    'close': 'Phit',
    'unknown_device': 'theilo mi device',
    'more': 'Adang',
    'lyrics': 'Hlaca',
    'upcoming_list': 'Ratdingmi List',
    'song_details': 'Hla Kawnglam',
    'share': 'Cheuh',
    'favorite': 'Duhbik',
  },
  'falam': {
    'app_name': 'Nix',
    'welcome': 'Welcome',
    'songs': 'Hla pawl',
    'favorites': 'Na duhmi',
    'settings': 'Siam rem nak',
    'choose_language': 'Tawing',
    'appearance': 'Ahmel',
    'dark_mode': 'A thim',
    'light_mode': 'A eng',
    'system_mode': 'System in',
    'color_scheme': 'Color',
    'about': 'Thuhla',
    'app_info': 'App thuhla',
    'version': 'Version',
    'developer': 'Siam tu',
    'license': 'License',
    'open_source': 'Open Source',
    'play': 'Phawn',
    'pause': 'Ding',
    'next': 'Hla hmai',
    'previous': 'Hla hnung',
    'shuffle': 'Aduh duhin',
    'repeat': 'Khirh sal',
    'now_playing': 'Play lai',
    'no_songs': 'Hla a um lo',
    'search': 'Hla hawl',
    'your_name': 'Na hming',
    'enter_name': 'Na hming ngan ta',
    'save': 'Save',
    'language': 'Tawng',
    'privacy_policy': 'Privacy Policy',
    'contact': 'Contact',
    ///////////
    'clear_data': 'Clear Data',
    'warning': 'Warning!',
    'delete_warning_msg':
        'Are you sure you want to delete all data? This cannot be undone.',
    'cancel': 'Ti sallo',
    'delete': 'Delete',
    'more': 'Adang',
    'github': 'GitHub',
    'email': 'Email',
    'theme_settings': 'Theme Setting',
    'theme_mode': 'Theme Mode',
    'light': 'A eng',
    'dark': 'A thim',
    'system_default': 'System bangin',
    'theme_colors': 'Theme Color',
    'pick_color': 'Color hril aw',
    'default_color_note': 'Default color cu Blue a si, Pink hnuai ah a um.',
    'choose_color': 'Color hril aw',
    'select': 'Ka hril',
    //////////////////////////////////////////
    'features': 'HmangThaNak :',
    'fea1': ' • Local Music Playback - ',
    'featu1': 'Plays audio from your device.',
    'fea2': ' • Favorites Management - ',
    'featu2': 'Easily add/remove favorite tracks.',
    'fea3': ' • Search & Sort - ',
    'featu3': 'Find songs quickly by name or artist.',
    'fea4': ' • Shuffle & Repeat - ',
    'featu4': 'Flexible playback options.',
    'fea5': ' • Custom Themes - ',
    'featu5': 'Light/Dark/System + color picker.',
    'fea6': ' • Responsive MiniPlayer - ',
    'featu6': 'Expandable with smooth animations.',
    'fea7': ' • Open Source - ',
    'featu7': 'Free, no ads, full transparency on GitHub.',
    'fea8': ' • Future Releases - ',
    'featu8': 'Officially coming to F-Droid and Google Play.',
    'contributors': 'Contributors',
    'developer_name': 'BawiCeu',
    'open_source_comu': 'Open Source Community',
    'check_for_updates': 'Check for Updates',
    'open_source_licenses': 'Open Source Licenses',
    'privacy_policy': 'Privacy Policy',
    'source_code_on_gitHub': 'Source Code on GitHub',
    //////
    'no_favorites_songs_yet': 'No favorites songs yet.',
    'songs_nav': 'Songs',
    'favorites_nav': 'Favorites',
    'playlist_nav': 'Play List',
    'search_hint': 'Search..',
    'user': 'User',
    'default': 'Default',
    'title_az_sort': 'Title (A-Z)',
    'title_za_sort': 'Title (Z-A)',
    'artist_sort': 'Title (A-Z)',
    'duration_sort': 'Duration (Shortest First)',
    'album': 'Album: ',
    'duration': 'Duration: ',
    'size': 'Size: ',
    'path': 'Path: ',
    'close': 'Close',
    'unknown_device': 'Unknown device',
    'more': 'More',
    'lyrics': 'Lyrics',
    'upcoming_list': 'UpComing List',
    'song_details': 'Song Details',
    'share': 'Share',
    'favorite': 'favorite',
  },
};
